### ISSUE TITLE
[Bug]: Client side error when viewing a project

### ISSUE THREAD

**Issue by Bashamega** [Zemerik/ZemShowcase#11]
### What happened?

When i click to view a project it returns a clients side error. I would like to fix it

### Add screenshots

![image](https://github.com/user-attachments/assets/e992c3b7-d902-4f61-9492-b6ee5b3d1de5)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zemerik** [comment]
Hey Adam, 

Thanks for opening this Issue and informing us about it, *would you like to be assigned the issue?*

I tried uploading a `.next` folder, which I had forgotten to commit, but that also did not fix the issue. Feel free to let me know if you have a solution, so that I can assign you the issue 👍

Regards, 
Zemerik

**Comment by Bashamega** [comment]
> Hey Adam,
> 
> Thanks for opening this Issue and informing us about it, _would you like to be assigned the issue?_
> 
> I tried uploading a `.next` folder, which I had forgotten to commit, but that also did not fix the issue. Feel free to let me know if you have a solution, so that I can assign you the issue 👍
> 
> Regards, Zemerik

First of all the .next folder should be ignored.
Secondly i can fix the problem with modifying the types.
It is a types error

**Comment by Zemerik** [comment]
Thanks Adam. Assigned to you as well 👍
